microsoft/go-mssqldb

queries_go19_test.go
token.go

SQL Server sends row count values in the `done` struct for non-select statements like `declare @d1 int = 1`. We will ignore those row counts for the rows affected messages.
Fixes [sqlcmd](https://github.com/microsoft/go-sqlcmd/issues/81)

ignore spurious row counts

---

examples/azuread-service-principal/service_principal.go

Fixes #23.
@shueybubbles opened after addressing comments for #25.

Add example for AAD Service Principal connection

---

README.md
appveyor.yml
bulkcopy.go
bulkcopy_test.go
mssql.go
mssql_go110_perf_test.go
mssql_go19.go
mssql_perf_test.go
queries_test.go

Fixes #16 
I'd like community input on #21. Changing the scan-to-interface{} behavior is fairly easy to do but it may have undesired side effects if apps are expecting `int64` in that scenario and could fail otherwise.

Use appropriate integer sizes for query parameters

---

examples/azuread-service-principal-authtoken/service_principal_authtoken.go
mssql.go

Refer to the example file (examples/azuread-service-principal-authtoken/service_principal_authtoken.go) to understand how it will work.
EOL CRLF difference is causing all the lines to be shown as changed, not sure if GitHub offers an option to ignore this while reviewing, suggestions are welcome.
Fixes #24.

Connect to a DB by directly supplying access token

---

README.md
msdsn/conn_str.go
msdsn/conn_str_go112.go
msdsn/conn_str_go112pre.go
msdsn/conn_str_test.go
tds.go

Fixes #33 
Adds `tlsmin` parameter to the connection string to enable use of 1.0 and 1.1 as needed.

add tlsmin connection parameter

---

README.md
appveyor.yml
examples/azuread-service-principal-authtoken/service_principal_authtoken.go
internal/np/namedpipe_windows.go
msdsn/conn_str.go
msdsn/extensions.go
namedpipe/namedpipe_windows.go
namedpipe/stub.go
namedpipe_test.go
net_go116_test.go
protocol.go
queries_test.go
sharedmemory/sharedmemory.go
sharedmemory/sharedmemory_windows.go
sharedmemory/stub.go
sharedmemory_test.go
tds.go
tds_test.go

Shared memory connections can be made for "." or "localhost" or for a host name that matches the value returned by `os.Hostname()`. Just import the `sharedmemory` package to enable it.
To put shared memory as the primary connection option, set it as the first entry in `msdsn.ProtocolParsers`. To force only a shared memory connection, use the `lpc:` prefix on the host name in the connection string or set the "protocol" parameter to "lpc" in an `msdsn.Config`.

Implement shared memory dialer

---

bad_server_test.go
tds.go

Currently the driver panic If the server sends bad prelogin connection data.
Added additional checks and unit tests to verify the behavior.
https://github.com/microsoft/go-mssqldb/issues/64

Added checks while reading prelogin for invalid data

---

CHANGELOG.md
README.md
msdsn/conn_str.go
namedpipe/namedpipe_windows.go
namedpipe_test.go
protocol.go
queries_test.go
tds.go
tds_test.go

1 - add a `pipe` parameter so users can encode it in a URL DSN
2 - avoid unneeded browser queries when TCP protocol is first in the dialer list

Fixes for named pipe dialer

---

CHANGELOG.md
protocol.go
protocol_go113.go
protocol_go113pre.go
tds_go113_test.go
tds_test.go

Then it's possible to assign error by errors.As to *net.OpError.
It allows us to determine if connection timeouted or was refused.

wrap connection error

---

tds_go113_test.go

Followup to #58 to skip the test on non-tcp connections

Test fix new wrap error

---

CHANGELOG.md
msdsn/conn_str.go
msdsn/conn_str_test.go

A change in fd44003 moved the code for setting p.Host down in the parse function, resulting in an empty p.Host value at the time of the creation of p.TLSConfig. I extracted the TLS parsing into a separate function and moved the TLSConfig creation to the end of the parsing function.
closes #93

Fixed #93: servername was not supplied to TLS cfg

---

CHANGELOG.md
README.md
msdsn/conn_str.go
msdsn/protocolparse_test.go
mssql.go
namedpipe/namedpipe_windows.go
namedpipe/stub.go
queries_go110_test.go
queries_go19_test.go
queries_test.go
sharedmemory/sharedmemory_windows.go
sharedmemory/stub.go
sharedmemory_test.go
tds.go

Fixes #108 
I've attempted to adhere to this spec for DAC: https://learn.microsoft.com/en-us/sql/database-engine/configure-windows/diagnostic-connection-for-database-administrators?view=sql-server-ver15
The doc confuses me a bit. I don't know how an app is supposed to tell the difference between `admin:<instance_name>` and `admin:<server_name>`
The driver requires the full `admin:server\instance` syntax or separate parameters for `server` and `protocol`.

Add admin protocol for DAC

---

CHANGELOG.md
README.md
mssql.go
protocol.go
tds_login_test.go
tds_test.go

If the custom dialer updates the transport to proxy the mssql connection, and only the proxy can reach the network that mssql is running in, then any local DNS resolution will fail.
To address this, this PR ensures the custom dialer is used, if defined, to resolve the DNS.
We've been using this logic on [Grafana's forked repo](https://github.com/grafana/go-mssqldb) for the past few months.

Allow for local dns resolution with a custom dialer

---

uniqueidentifier.go
uniqueidentifier_test.go

Addresses #92 
- The existing MarshalText() for the UniqueIdentifier type had a bad signature. It omitted returning an error that the interface expects.
- Added UnmarshalJSON() interface to the UniqueIdentifier type with a test as well

Fixes MarshalText and adds UnmarshalJSON interface for UniqueIdentifier

---

version.go

I've neglected updating the version number in our login packet for a few releases.
This updates it to 1.4. Once this goes in I will push the tag.

prep for tag 1.4

---

CHANGELOG.md
protocol.go
version.go

I couldn't find a standard package for converting the style of ASCII encoding that SQL uses into a UTF8 Go string, nor could I find something to convert from UTF8 to that ASCII byte array. `strconv.QuoteToASCII` is the only common conversion function I could find.
I was hoping to change the browser message we use to `4` which takes the instance name as parameter, but without the conversion to ASCII byte array I can use it.

Fix: Handle extended chars in SQL instance names

---

CHANGELOG.md
README.md
azuread/configuration.go

feat: Add device code and Az CLI auth types to azuread

---

internal/cp/charset.go

This PR changes how returning string is created in `CharsetToUTF8` function.
<details>
<summary>Code</summary>
```
import (
"strings"
)
var str string
func CharsetToUTF8(s []byte) {
buf := make([]rune, 0, len(s))
for i := 0; i < len(s); i++ {
ch := cp950.sb[s[i]]
if ch == -1 {
if i+1 == len(s) {
ch = 0xfffd
} else {
n := int(s[i+1]) + (int(s[i]) << 8)
i++
var ok bool
ch, ok = cp950.db[n]
if !ok {
ch = 0xfffd
}
}
}
buf = append(buf, ch)
}
str = string(buf)
}
func CharsetToUTF8_2(s []byte) {
b := strings.Builder{}
b.Grow(len(s))
for i := 0; i < len(s); i++ {
ch := cp950.sb[s[i]]
if ch == -1 {
if i+1 == len(s) {
ch = 0xfffd
} else {
n := int(s[i+1]) + (int(s[i]) << 8)
i++
var ok bool
ch, ok = cp950.db[n]
if !ok {
ch = 0xfffd
}
}
}
b.WriteRune(ch)
}
str = b.String()
}
```
Benchmarks:
``` …
```

fix(CharsetToUTF8): use strings.Builder

---

msdsn/conn_str.go
msdsn/conn_str_test.go

Add support for DER certificates

---

CHANGELOG.md
aecmk/akv/keyprovider.go
aecmk/akv/keyprovider_test.go
aecmk/error.go
aecmk/keyprovider.go
aecmk/localcert/keyprovider.go
aecmk/localcert/keyprovider_darwin.go
aecmk/localcert/keyprovider_go117_windows_test.go
aecmk/localcert/keyprovider_linux.go
aecmk/localcert/keyprovider_windows.go
alwaysencrypted_test.go
encrypt.go
internal/certs/certs_windows.go
tds_go110_test.go
token.go
version.go

- Pass along the `context` for running queries so key decryption participates in timeouts etc
- Return errors from the key providers directly instead of panicking
- Prep for v1.7
Fixes #144

Replace panic with returning errors from key decryption providers

---

README.md
msdsn/conn_str.go
msdsn/conn_str_test.go
protocol.go

Fixes #158 if the connection string sets multisubnetfailover to false.  
I believe most other libraries default this to false but to prevent a breaking change I kept the current behavior (defaulted to true).

fix: Added multisubnetfailover option, set to false to prevent issue #158

---

bulkcopy.go
queries_go19_test.go
rpc.go
tvp_go19.go
types.go

Fixes https://github.com/microsoft/go-mssqldb/issues/161 .

Cut string output parameter fix

---

README.md
alwaysencrypted_test.go
mssql.go
mssql_go19.go
queries_go19_test.go
queries_test.go

Previously the driver would use `char(1)` as the parameter declaration for all null-valued parameters. This change preserves type information for `driver.Valuer` implementations. It has the additional benefit of declaring guid parameters as `uniqueidentifier` type instead of `varbinary[16]`.

Fix: Support nullable types in Always Encrypted

---

azuread/configuration.go

Fixes #197 
Also cleans up the file based on lint

Fix: Use correct scope for Entra authentication

---

queries_test.go
types.go

- Adds support for hierarchyid, geometry and geography SQL type.
- Currently a panic is thrown when the system tries to scan any UDT (user defined type)
- This has been brought up many times (e.g. [167](https://github.com/microsoft/go-mssqldb/issues/167), [79](https://github.com/microsoft/go-mssqldb/issues/79))
- Doesn't make sense to have a official driver that doesn't support all official SQL types.
- There are some forks such as [this one](https://github.com/bytebase/go-mssqldb) to try to solve this issue and the solutions seems to work correctly for every case.
- I have tested the solution for all proposed types and have implemented a [library to handle hierarchyid](https://github.com/tentone/hierarchyid) encoding and decoding in Go, that has been developed with the modified driver.

Support for UDT (hierarchyid, geometry and geography)

---

tds.go
tds_test.go

#173 describes a bug when a database name is provided that does not exist, but the connections remain open and db.Close() doesn't help to close them. 
This PR is supposed to fix this issue by closing connection before returning error. The connection is unusable despite the message from the server like `Cannot open database "shmaster" that was requested by the login. Using the user default database "master" instead` - db.PingContext returns an error, but connections remain open

Connection not closed when database name is incorrect #173 fix

---

azuread/configuration.go
azuread/configuration_test.go

Before this PR certificate-based authentication (in case of a `ActiveDirectoryServicePrincipal` or `ActiveDirectoryApplication` fed auth) would panic (nil pointer dereference at `github.com/microsoft/go-mssqldb@v1.7.2/azuread/configuration.go:228`) because of wrong error checks.

Fix error checks during certificatePath reading and parsing in azuread

---

uniqueidentifier_null.go
uniqueidentifier_null_test.go

* as literal name according RFC 7159
* remove panic: encoding/hex: invalid byte: U+006E 'n'

Add JSON-encoded version of NULL uniqueidentifier

---

types.go
types_date_and_time_test.go

This PR fixes an issue: https://github.com/microsoft/go-mssqldb/issues/181

DATETIME: fix 1/300 of a seconds rounding logic (Bulk Copy related)

---

go.mod
go.sum

bump [github.com/golang-jwt/jwt/v5 v5.2.1 => v5.2.2](https://github.com/golang-jwt/jwt/releases/tag/v5.2.2) given the vulnerability described by the [CVE-2025-30204](https://www.cve.org/CVERecord?id=CVE-2025-30204). ([Go Vuln Report](https://pkg.go.dev/vuln/GO-2025-3553))
Description:
Starting in golang-jwt version 3.2.0 and prior to versions 5.2.2 and 4.5.2, the function parse.ParseUnverified splits (via a call to strings.Split) its argument (which is untrusted data) on periods. As a result, in the face of a malicious request whose Authorization header consists of Bearer followed by many period characters, a call to that function incurs allocations to the tune of O(n) bytes (where n stands for the length of the function's argument), with a constant factor of about 16. This issue is fixed …

bump: github.com/golang-jwt/jwt/v5 v5.2.1 => v5.2.2

---

internal/github.com/swisscom/mssql-always-encrypted/pkg/alwaysencrypted_test.go
mssql_perf_test.go
tds.go
token.go

`io/ioutil` has been deprecated since go 1.16, in favour of `io`.

fix: replace ioutil with io everywhere

---

lastinsertid_example_test.go

Build's started failing under Go v1.24 which were traced back to a new 'go vet' analyser. Changing the function name in this patch marked it as an example for the package as a whole - as long as the part under the underscore is in lower-case.
See: https://go.dev/blog/examples

Work around build error introduced by the new 'go vet' tests analyser

---

mssql.go
mssql_test.go

Fix: https://github.com/microsoft/go-sqlcmd/issues/569

isProc: added `COMMIT` and `ROLLBACK` command to the builtin commands

---

.pipelines/TestSql2017.yml
aecmk/akv/keyprovider.go
aecmk/akv/keyprovider_test.go
alwaysencrypted_akv_test.go
azuread/configuration_test.go
internal/akvkeys/utils.go
tds_test.go

now that `AzurePipelinesCredential` is available, our internal ADO pipeline can use it.

Restore tests against Azure resources

---

CHANGELOG.md
mssql.go
token.go
version.go

My first attempt at a fix was not correct. This change addresses the root cause - when `rowsQ.HasNextResultSet()` returns `false`, the `sql/data` package calls `Close` on it immediately, leading to the context getting cancelled and tokens dropped.
For some reason, in my initial implementation I wrote a comment with the correct behavior to always return `true` yet the body of the method didn't match and I can't recall why.
I've changed the method to match the comment and tested with a new sqlcmd build. I can't reproduce the hang.
I've also reordered the posting of `MsgRowsAffected` to precede sending the `done` event to the channel, to assure it can be processed even if the context cancels when the done is received.

Fix: make the message queue model work correctly

---

bulkcopy.go
bulkcopy_test.go

I noticed that after a failed bulk copy, statements would "randomly" have no effect. I tracked this down to the bulk copy code not ensuring FMTONLY ON was actually being reset in the case of a failure, which was causing the next statement executed in that session to be nullified.

bulkcopy: always reset FMTONLY in case of failure
